name: Run PlayWright Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Download playwright browser
        run: npx playwright install



      - name: Scrap ids
        run: |
          tsc scapper/htmlScrapper.ts
          node scapper/htmlScrapper.js
